apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: your-namespace
  name: service-reader
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]




---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: your-service-account
  namespace: your-namespace


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-binding
  namespace: your-namespace
subjects:
- kind: ServiceAccount
  name: your-service-account
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
